ExamMvc.Web/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ExamMvc.Model;
using ExamMvc.Data;
using Kendo.Mvc.UI;
using ExamMvc.Web.Models;
using System.ComponentModel.DataAnnotations;
using Kendo.Mvc.Extensions;

namespace ExamMvc.Web.Controllers
{
    [Authorize(Roles="Admin")]
    public class CategoryController : BaseController
    {
        public ActionResult Index()
        {
            return View("KendoGrid");
        }

        
        public ActionResult Create([DataSourceRequest] DataSourceRequest request, CategoryViewModel category)
        {
            if (category != null)
            {
                if (this.Data.Categories.All().Any(cat => cat.Name.ToLower() == category.Name.ToLower()))
                {
                    ModelState.AddModelError("Name", "Category Name already exists");
                }

                if (ModelState.IsValid)
                {
                    Category categoryEntity = new Category()
                    {
                        Name = category.Name,
                    };

                    this.Data.Categories.Add(categoryEntity);
                    this.Data.SaveChanges();

                    category.Id = categoryEntity.Id;
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest,
                       ModelState.FirstOrDefault(x => x.Value.Errors.Count > 0).Value.Errors.FirstOrDefault().ErrorMessage);
                }
            }
            return Json(new[] { category }.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public JsonResult Delete([DataSourceRequest] DataSourceRequest request,
             CategoryViewModel category)
        {
            this.Data.Categories.Delete(category.Id);
            this.Data.SaveChanges();
            return Json(new[] { category }.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCategories([DataSourceRequest] DataSourceRequest request)
        {
            var categories = this.Data.Categories.All().Select(CategoryViewModel.FromCategory);
            return Json(categories.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public ActionResult Update([DataSourceRequest] DataSourceRequest request,
            CategoryViewModel categoryModel)
        {
            if (categoryModel != null)
            {
                if (this.Data.Categories.All()
                    .Any(cat => cat.Name.ToLower() == categoryModel.Name.ToLower()
                    && cat.Id != categoryModel.Id))
                {
                    ModelState.AddModelError("Name", "Category Name already exists");
                }

                var categoryEntity = this.Data.Categories.GetById(categoryModel.Id);

                if (categoryEntity == null)
                {
                    ModelState.AddModelError("CategoryId", "Invalid Category");
                }

                if (ModelState.IsValid)
                {
                    categoryEntity.Name = categoryModel.Name;
                    this.Data.Categories.Update(categoryEntity);
                    this.Data.SaveChanges();
                }
                else
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest,
                       ModelState.FirstOrDefault(x => x.Value.Errors.Count > 0).Value.Errors.FirstOrDefault().ErrorMessage);
                }
            }

            return Json(new[] { categoryModel }.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }
    }
}

ExamMvc.Web/Controllers/CommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ExamMvc.Model;
using ExamMvc.Data;

namespace ExamMvc.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CommentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Ticket).Include(c => c.User);
            return View(comments.ToList());
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Comment model)
        {
            var comment = db.Comments.FirstOrDefault(m => m.Id == model.Id);
            if (comment != null)
            {
                comment.Content = model.Content;
            }
            else
            {
                ModelState.AddModelError("Comment", "Comment not found! Updating failed.");
            }

            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

ExamMvc.Web/Controllers/TicketsLoggedUserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ExamMvc.Model;
using ExamMvc.Data;
using ExamMvc.Web.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Kendo.Mvc.UI;
using Kendo.Mvc.Extensions;

namespace ExamMvc.Web.Controllers
{
    [Authorize]
    public class TicketsLoggedUserController : BaseController
    {
        private IQueryable<TicketListModel> GetAllTickets()
        {
            var data = this.Data.Tickets.All().Select(x => new TicketListModel()
            {
                Id = x.Id,
                AuthorName = x.Author.UserName,
                CategoryName = x.Category.Name,
                Priority = x.Priority,
                Title = x.Title,
            }).OrderBy(x => x.Id);

            return data;
        }

        public ActionResult KendoList()
        {
            return View();
        }

        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(this.Data.Categories.All(), "Id", "Name");
            PopulatePriorities();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TicketCreateModel ticket)
        {
            if (ModelState.IsValid)
            {
                string userId = this.User.Identity.GetUserId();
                ApplicationUser user = this.Data.Users.All().FirstOrDefault(x => x.Id == userId);
                Category cat = this.Data.Categories.All().FirstOrDefault(x => x.Id == ticket.CategoryId);

                Ticket newTicket = new Ticket()
                {
                    Author = user,
                    Category = cat,
                    Priority = ticket.Priority,
                    Title = ticket.Title,
                    ScreenshotUrl = ticket.ScreenshotUrl,
                    Description = ticket.Description,
                };

                this.Data.Tickets.Add(newTicket);
                user.Points += 1;
                this.Data.SaveChanges();

                return RedirectToAction("KendoList");
            }

            ViewBag.CategoryId = new SelectList(this.Data.Categories.All(), "Id", "Name", ticket.CategoryId);
            PopulatePriorities();

            return View(ticket);
        }

        public JsonResult GetTickets([DataSourceRequest] DataSourceRequest request)
        {
            return Json(this.GetAllTickets().ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetTicketsByCategoryData()
        {
            var result = this.Data.Categories
                .All()
                .Select(x => new SubmitSearchModel
                {
                    Name = x.Name,
                    Id = x.Id,
                });

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Search(int? catId)
        {
            var result = this.Data.Tickets.All();
            if (catId != null && catId != 0)
            {
                result = result.Where(x => x.CategoryId == catId.Value);
            }

            var endResult = result.Select(x => new TicketListModel
            {
                Id = x.Id,
                AuthorName = x.Author.UserName,
                CategoryName = x.Category.Name,
                Priority = x.Priority,
                Title = x.Title,
            }).OrderBy(x => x.Id);

            return View("SearchResults", endResult);
        }

        private void PopulatePriorities()
        {
            IList<SelectListItem> resultList = new List<SelectListItem>();
            foreach (Priority p in Enum.GetValues(typeof(Priority)))
            {
                SelectListItem item;
               
                    item = new SelectListItem()
                   {
                       Selected = false,
                       Text = p.ToString(),
                       Value = ((int)p).ToString(),
                   };
                resultList.Add(item);
            }

            // set default priority
            resultList.First(x => x.Value == "1").Selected = true;
            ViewBag.Priority = resultList;
        }
    }
}

ExamMvc.Web/Views/Shared/_CommentPartial.cshtml
@model ExamMvc.Web.Models.CommentViewModel

    <p><strong>@Model.AuthorUsername : </strong> @Model.Content</p>

ExamMvc.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/kendo")

    @Scripts.Render("~/bundles/kendo")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ticketing System", "Index", "Home", null, new { @class = "brand" })
                <div class="nav-collapse collapse">
                    <ul class="nav" id="MainMenu">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>

                        @if (this.User.Identity.IsAuthenticated)
                        {
                            <li>@Html.ActionLink("Add Ticket", "Create", "TicketsLoggedUser")</li>
                            <li>@Html.ActionLink("View All Tickets", "KendoList", "TicketsLoggedUser")</li>
                        }
                        @if (this.User.IsInRole("Admin"))
                        { <li>Administrator
                              <ul class="nav" id="AdminMenu"> 

                                  <li>@Html.ActionLink("Manage Categories", "Index", "Category")</li>
                                  <li>@Html.ActionLink("Manage Comments", "Index", "Comments")</li>
                              </ul>
                            </li>
                        }
                        
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ticketing System ASP.NET Application</p>
        </footer>
    </div>
  
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>

    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        $("#MainMenu").kendoMenu();
    </script>
</body>
</html>